name: Dummy

on: 
  workflow_dispatch:
    inputs:
      Build-Version:
        required: true
      Environment:
        type: environment

  
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
       
    strategy:
      fail-fast: false
      matrix:
        Plan: ["SYDATA-Purchase Order"]
        
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d_%H_%M_%S')" >> $GITHUB_OUTPUT
      
    - name: Remove space from Test Plan
      id: TestPlanName
      run: |
        temp="${{matrix.Plan}}"	
        echo "TestPlanName=$(echo ${temp// /_})" >> $GITHUB_OUTPUT
        
    - name: Remove forward slash from Test Plan
      id: PlanName
      run: |
        temp="${{ steps.TestPlanName.outputs.TestPlanName}}"	
        echo "PlanName=$(echo ${temp/\//-})" >> $GITHUB_OUTPUT

 
    - name: Send Slack Message
      run: |
        echo "The selected color is ${{ steps.PlanName.outputs.PlanName }}"      


    - uses: actions/checkout@v2.5.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'adopt'
        java-version: 8
  
    - name: Test output
      run: |
        echo '${{ job.status }}' === 'success' ? 'Passed' : '${{ job.status }}' === 'failure' ? 'Failed' : 'cancelled'
