name: Execute_All_API

on: 
  workflow_dispatch:
    inputs:
      Build-Version:
        required: true
      Environment:
        type: environment
  
jobs:
  Execution-Start-Slack-Notification:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.Environment }}
    
    steps:
    - name: Send Slack Message-Personal Slack
      uses: archive/github-actions-slack@v2.4.0
      id: send-message
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN_RSTKMFG }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_RSTKMFG }}
        slack-text: Automation Script execution started for ERP Version-${{ github.event.inputs.Build-Version }} On ${{ github.event.inputs.Environment }} by ${{ github.actor }}

    - name: Send "Slack Message" Result
      run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"
 
  workflow-1:
    needs: Execution-Start-Slack-Notification  
    uses: ./.github/workflows/API-1.yml
    secrets: inherit
  
  workflow-2:
    if: success() || failure()
    needs: workflow-1
    uses: ./.github/workflows/API-2.yml
    secrets: inherit

  Execution-CompletedNotification:
    if: ${{ always() }}  
    needs: [workflow-1,workflow-2]  
    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_RSTKMFG }}

    steps:
    - name: Send Slack Message-Personal Slack
      uses: archive/github-actions-slack@v2.4.0
      id: send-message
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN_RSTKMFG }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_RSTKMFG }}
        slack-text: Execution Completed. Please visit GitHub Action for more details. 

    - name: Send "Slack Message" Result
      run: echo "Data - ${{ steps.send-message.outputs.slack-result }}"
    
    - name: Get Build URL
      uses: actions/checkout@v3.1.0
    - run: echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" > buildURL.log
      
    - name: Send build URL to slack
      uses: adrey/slack-file-upload-action@1.0.5
      with:
        token: $ {{ secrets.SLACK_TOKEN_RSTKMFG }}
        path: buildURL.log
        channel: provar_notification
