name: temp

on: 
  workflow_dispatch:
    inputs:
      Build-Version:
        required: true
      Environment:
        type: environment
  
jobs:
  Execution-Start-Slack-Notification:
    runs-on: ubuntu-latest
    environment: $ {{ github.event.inputs.Environment }}
    
    steps:
    - name: Send "Slack Message" Result
      run: echo "{{jobs.Execution-Start-Slack-Notification.conclusion}}"

    - name: Get Build URL
      uses: actions/checkout@v2.5.0
      if: ${{ always() }}
    - run: echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" > DummyURL.log

  Execution-CompletedNotification:
    if: ${{ !cancelled() }}  
    needs: [Execution-Start-Slack-Notification]  

    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_RSTKMFG }}
       
    steps:   
      - name: Get Build URL
        uses: actions/checkout@v2.5.0
        if: ${{ always() }}
      - run: cat DummyURL.log
            
      - name: Get Build URL
        uses: actions/checkout@v2.5.0
        if: ${{ always() }}
      - run: echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" > buildURL.log
