name: TimeZoneTest

on: 
  workflow_dispatch:

  
jobs:
  Execution-Start-Slack-Notification:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.Environment }}
    
    steps:
    - name: Test Timez zone
      run: |
        echo "Today is $(date)"
        sudo timedatectl set-timezone Asia/Calcutta
        echo "Date After TimeZoneChange $(date)"
